Controllers/LogoutController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab3.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            var name = HttpContext.Session.GetString("Username");
            Trace.WriteLine($"{DateTime.Now:HH:mm:ss}: {name} left");
            HttpContext.Session.Remove("Username");
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/SigninController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab3.Controllers
{
    public class SigninController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(User user)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (UserProvider.IsAuthorizedUser(user.Name, user.Password))
            {
                HttpContext.Session.SetString("Username", user.Name);
                Trace.WriteLine($"{DateTime.Now.ToString("HH:mm:ss")}: {user.Name} successfully authorized");
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("Password", "Помилка у логіні або паролі");
            return View();
        }
    }
}

Controllers/Task1Controller.cs
using Lab3.Models;
using static Lab3.Models.DataProvider;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Lab3.Controllers;

public class Task1Controller : Controller
{
    private List<SelectListItem>? _availableSubjects;

    private void GetSubjects()
    {
        if (_availableSubjects is not null) return;

        var allSubjects = new SortedSet<string>();
        foreach (var ratingField in Ratings)
            allSubjects.Add(ratingField.SubjectName);

        _availableSubjects = new List<SelectListItem> { new() { Text = "Усі предмети", Value = "Усі предмети" } };

        foreach (var subject in allSubjects)
            _availableSubjects.Add(new SelectListItem(subject, subject));
    }

    private static int GetMark(int firstMark, int secondMark)
    {
        var averageMark = (firstMark + secondMark) / 2f;
        return averageMark switch
        {
            < 35 => 1,
            < 60 => 2,
            < 74 => 3,
            < 90 => 4,
            _ => 5
        };
    }


    public IActionResult Index(string? selectedSubject)
    {
        GetSubjects();
        var tuple = new List<(string name, string? group, int? mark)>();
        var sortedStudents = new List<Student>(Students);
        sortedStudents.Sort((student1, student2) => String.Compare(student1.Name, student2.Name));

        foreach (var student in sortedStudents)
        {
            var rating = RatingsDict.GetValueOrDefault((student.Id, selectedSubject));
            //var aveMark = (rating.PointsFirstModule + rating.PointsSecondModule) / 2;
            if (selectedSubject is null)
            {
                foreach (var VARIABLE in Rat)
                {
                    
                }
            }

            if (selectedSubject is null || (GetMark(rating.PointsFirstModule, rating.PointsSecondModule) == 4 &&
                                            rating.SubjectName == selectedSubject))
                tuple.Add((student.Name, student.Group, rating.PointsFirstModule));
        }

        var viewModel = new Task1ViewModel
            { Tuple = tuple, Subjects = _availableSubjects, SubjectString = selectedSubject ?? "Усі предмети" };
        return View(viewModel);
    }


    [HttpPost]
    public IActionResult Index(Task1ViewModel task1ViewModel)
    {
        if (!ModelState.IsValid)
        {
            RedirectToAction("Index");
        }

        return Index(task1ViewModel.SubjectString);
    }
}

Controllers/Task2Controller.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using static Lab3.Models.DataProvider;

namespace Lab3.Controllers;

public class Task2Controller : Controller
{
    // GET
    public IActionResult Index()
    {
        var idAverages = new Dictionary<int, (int,int)>();
        
        foreach (var rating in Ratings)
        {
            if (!idAverages.ContainsKey(rating.Id))
            {
                idAverages[rating.Id] = (0,0);
            }

            var x = idAverages[rating.Id];
            idAverages[rating.Id] = (x.Item1 + rating.PointsFirstModule, x.Item2 + 1);
        }

        // Find the maximum of the averages
        var maxAverage = int.MinValue;
        foreach (var (sum,count) in idAverages.Values)
        {
            maxAverage = int.Max(maxAverage, sum / count);
        }

        var studentNames = new List<string>();

        foreach (var (k,v) in idAverages)
        {
            if (v.Item1 / v.Item2 == maxAverage)
                studentNames.Add(StudentsDict[k].Name);
        }
        var viewModel = new Task2ViewModel
        {
            StudentNames = studentNames,
            MaxRating = maxAverage,
        };
        return View(viewModel);
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Lab3.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark bg-opacity-75 border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand text-warning" asp-area="" asp-controller="Home" asp-action="Index">Lab3</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                @if (!Context.Session.Keys.Contains("Username"))
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Signin" asp-action="Index">Вхід</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Signup" asp-action="Index">Реєстрація</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Ratings" asp-action="Index">Ratings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Task1" asp-action="Index">Task1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Task2" asp-action="Index">Task2</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Logout" asp-action="Index">Вихід</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Lab3
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>