Controllers/SigninController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab3.Controllers
{
    public class SigninController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(User user)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (UserProvider.IsAuthorizedUser(user.Name, user.Password))
            {
                HttpContext.Session.SetString("Username", user.Name);
                Trace.WriteLine($"{DateTime.Now.ToString("HH:mm:ss")}: {user.Name} successfully authorized");
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("Password", "Помилка у логіні або паролі");
            return View();
        }
    }
}

Controllers/SignupController.cs
using System.Diagnostics;
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab3.Controllers
{
    public class SignupController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Index(User newUser)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (UserProvider.HasAccount(newUser.Name))
                ModelState.AddModelError("name", $"Користувач {newUser.Name} вжє зареєстрований. Спробуйте інше ім'я");
            else if (UserProvider.TryAddUser(newUser))
            {
                Trace.WriteLine($"{DateTime.Now:HH:mm:ss}: \"{newUser.Name}\" is registered");
                HttpContext.Session.SetString("Username", newUser.Name);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("name", $"Збій системи. Спробуйте зареєструватися пізніше");
            }

            return View();
        }
    }
}

Views/Signin/Index.cshtml
@model Lab3.Models.User

@{
ViewBag.Title = "Вхід";
Layout = "_Layout";
}

<h4>Вхід у систему</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Index" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Ім'я</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <label asp-for="Password" class="control-label">Пароль</label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="width:100px">Увійти</button>
            </div>
            <br />
            <div>
                <p>Відсутній акаунт? <a asp-controller="Signup" asp-action="Index"><b>Реєстрація</b></a></p>
            </div>
        </form>
    </div>
</div>

@*@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}
*@